tcmsg/sched_htb: rate and ceil are optional
Since commit b731fca9d2a3f598145d5f41fa04f7b3ae32ac88 rate cannot be
None anymore:

TypeError: '>=' not supported between instances of 'NoneType' and 'int'